services:
  db:
    image: postgres:16.0
    ports:
      - '12432:5432'
    environment:
      POSTGRES_USER: angular
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: angular_db
    volumes:
      - postgres_data2222:/var/lib/postgresql/data

volumes:
  postgres_data2222: